version: 2
jobs:
    build:
        working_directory: /opt/demo
        parallelism: 1
        shell: /bin/bash --login
        docker:
        - image: simonmcc/circleci-ubuntu-trusty:latest
          command: /bin/cat
        steps:
        - checkout
        - run: uname -a
        - run: id
        - run: ls /
        - run: pwd
