version: 2
jobs:
    build:
        working_directory: /opt/demo
        parallelism: 1
        shell: /bin/bash --login
        docker:
        - image: simonmcc/circleci-ubuntu-trusty:latest
          command: /bin/cat
        - image: circleci/mysql:5.6.45
          environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: passw0rd

        steps:
        - checkout
        - run: uname -a
        - run: id
        - run: ls /
        - run: pwd
        - run: apt-get install -y mysql-client-5.6
        - run: mysql --protocol tcp -u user --password=passw0rd -e "show databases"
